sylius_twig_hooks:
  hooks:
    'sylius_shop.base.header.content':
      eiling_io_searchbox:
        template: '@EilingIoSyliusBatteryIncludedPlugin/shop/header/_searchbox.html.twig'
        priority: 250
    'sylius_shop.product.show.content.product_listing':
      eiling_io_product_recommendation:
        component: 'EilingIo:ProductRecommendation'
        props:
          productDetail: '@=_context.product'
        priority: 250
    'sylius_shop.base.offcanvas.cart.body':
      eiling_io_offcanvas_cart_recommendation:
        component: 'EilingIo:OffcanvasCartRecommendation'
        props:
          cartDetail: '@=_context.cart'
        priority: -10
    'sylius_shop.cart.index.content':
      eiling_io_cart_recommendation:
        component: 'EilingIo:CartRecommendation'
        props:
          cartDetail: '@=_context.cart'
        priority: 50
      suggested_products:
        enabled: false

twig_component:
  defaults:
    EilingIo\SyliusBatteryIncludedPlugin\Twig\Components\:
      name_prefix: 'EilingIo'